spring:
  datasource:
    url: ${prop.spring.datasource.url}
    username: ${prop.spring.datasource.username}
    password: ${prop.spring.datasource.password}
  jooq:
    sql-dialect: POSTGRES
  flyway:
    baselineOnMigrate: true

app:
  jwt:
    secret: ${prop.app.jwt.secret}
    expiration-ms: 86400000   # 24 hours
