#spring.config.import=application-dev-secrets.properties

prop.spring.datasource.url=jdbc:postgresql://localhost:5432/rosebot
prop.spring.datasource.username=rosebot
prop.spring.datasource.password=rosebot
prop.ai.openai.api-key=not-needed
prop.ai.openai.chat.base-url=http://localhost:11434
prop.ai.openai.chat.model=Qwen3.5-9B-Q5_K_M.gguf
prop.ai.openai.embedding.base-url=http://localhost:11435
prop.ai.openai.embedding.model=nomic-embed-text-v1.5-Q8_0.gguf
