spring:
  datasource:
    url: ${prop.spring.datasource.url}
    username: ${prop.spring.datasource.username}
    password: ${prop.spring.datasource.password}
  jooq:
    sql-dialect: POSTGRES
  ai:
    ollama:
      base-url: ${prop.ai.ollama.base-url}
      chat:
        model: qwen3:8b
        options:
          temperature: 0.2
          num_ctx: 8192
      embedding:
        model: nomic-embed-text

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health
