/*
 * This file is generated by jOOQ.
 */
package jooq.enums


import jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class ArticleCategory(@get:JvmName("literal") public val literal: String) : EnumType {
    POLITICS("POLITICS"),
    BUSINESS("BUSINESS"),
    TECHNOLOGY("TECHNOLOGY"),
    SCIENCE_AND_HEALTH("SCIENCE_AND_HEALTH"),
    WORLD("WORLD"),
    SOCIETY("SOCIETY"),
    ENTERTAINMENT("ENTERTAINMENT"),
    SPORTS("SPORTS");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "article_category"
    override fun getLiteral(): String = literal
}
