/*
 * This file is generated by jOOQ.
 */
package jooq.enums

import jooq.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class ClusterStatus(
    @get:JvmName("literal") public val literal: String,
) : EnumType {
    PENDING("PENDING"),
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE"),
    ;

    override fun getCatalog(): Catalog? = schema.catalog

    override fun getSchema(): Schema = Public.PUBLIC

    override fun getName(): String = "cluster_status"

    override fun getLiteral(): String = literal
}
