/*
 * This file is generated by jOOQ.
 */
package jooq.enums

import jooq.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class SourceType(
    @get:JvmName("literal") public val literal: String,
) : EnumType {
    NEWS("NEWS"),
    REDDIT("REDDIT"),
    TWITTER("TWITTER"),
    ;

    override fun getCatalog(): Catalog? = schema.catalog

    override fun getSchema(): Schema = Public.PUBLIC

    override fun getName(): String = "source_type"

    override fun getLiteral(): String = literal
}
