/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.Keys;
import jooq.Public;
import jooq.tables.User.UserPath;
import jooq.tables.records.AppStateRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppState extends TableImpl<AppStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_state</code>
     */
    public static final AppState APP_STATE = new AppState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppStateRecord> getRecordType() {
        return AppStateRecord.class;
    }

    /**
     * The column <code>public.app_state.id</code>.
     */
    public final TableField<AppStateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.app_state.user_id</code>.
     */
    public final TableField<AppStateRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.app_state.last_visited_at</code>.
     */
    public final TableField<AppStateRecord, OffsetDateTime> LAST_VISITED_AT = createField(DSL.name("last_visited_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.app_state.updated_at</code>.
     */
    public final TableField<AppStateRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AppState(Name alias, Table<AppStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppState(Name alias, Table<AppStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_state</code> table reference
     */
    public AppState(String alias) {
        this(DSL.name(alias), APP_STATE);
    }

    /**
     * Create an aliased <code>public.app_state</code> table reference
     */
    public AppState(Name alias) {
        this(alias, APP_STATE);
    }

    /**
     * Create a <code>public.app_state</code> table reference
     */
    public AppState() {
        this(DSL.name("app_state"), null);
    }

    public <O extends Record> AppState(Table<O> path, ForeignKey<O, AppStateRecord> childPath, InverseForeignKey<O, AppStateRecord> parentPath) {
        super(path, childPath, parentPath, APP_STATE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AppStatePath extends AppState implements Path<AppStateRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppStatePath(Table<O> path, ForeignKey<O, AppStateRecord> childPath, InverseForeignKey<O, AppStateRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppStatePath(Name alias, Table<AppStateRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppStatePath as(String alias) {
            return new AppStatePath(DSL.name(alias), this);
        }

        @Override
        public AppStatePath as(Name alias) {
            return new AppStatePath(alias, this);
        }

        @Override
        public AppStatePath as(Table<?> alias) {
            return new AppStatePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AppStateRecord, Long> getIdentity() {
        return (Identity<AppStateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AppStateRecord> getPrimaryKey() {
        return Keys.APP_STATE_PKEY;
    }

    @Override
    public List<UniqueKey<AppStateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.APP_STATE_USER_ID_KEY);
    }

    @Override
    public List<ForeignKey<AppStateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_STATE__APP_STATE_USER_ID_FKEY);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.APP_STATE__APP_STATE_USER_ID_FKEY, null);

        return _user;
    }

    @Override
    public AppState as(String alias) {
        return new AppState(DSL.name(alias), this);
    }

    @Override
    public AppState as(Name alias) {
        return new AppState(alias, this);
    }

    @Override
    public AppState as(Table<?> alias) {
        return new AppState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppState rename(String name) {
        return new AppState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppState rename(Name name) {
        return new AppState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppState rename(Table<?> name) {
        return new AppState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState where(Condition condition) {
        return new AppState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
