/*
 * This file is generated by jOOQ.
 */
package jooq.tables

import jooq.Public
import jooq.keys.APP_STATE_PKEY
import jooq.keys.APP_STATE_USER_ID_KEY
import jooq.keys.APP_STATE__APP_STATE_USER_ID_FKEY
import jooq.tables.User.UserPath
import jooq.tables.records.AppStateRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AppState(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AppStateRecord>?,
    parentPath: InverseForeignKey<out Record, AppStateRecord>?,
    aliased: Table<AppStateRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<AppStateRecord>(
        alias,
        Public.PUBLIC,
        path,
        childPath,
        parentPath,
        aliased,
        parameters,
        DSL.comment(""),
        TableOptions.table(),
        where,
    ) {
    companion object {
        /**
         * The reference instance of <code>public.app_state</code>
         */
        val APP_STATE: AppState = AppState()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AppStateRecord> = AppStateRecord::class.java

    /**
     * The column <code>public.app_state.id</code>.
     */
    val ID: TableField<AppStateRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.app_state.user_id</code>.
     */
    val USER_ID: TableField<AppStateRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.app_state.last_visited_at</code>.
     */
    val LAST_VISITED_AT: TableField<AppStateRecord, OffsetDateTime?> =
        createField(DSL.name("last_visited_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.app_state.updated_at</code>.
     */
    val UPDATED_AT: TableField<AppStateRecord, OffsetDateTime?> =
        createField(
            DSL.name("updated_at"),
            SQLDataType
                .TIMESTAMPWITHTIMEZONE(
                    6,
                ).nullable(false)
                .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this,
            "",
        )

    private constructor(alias: Name, aliased: Table<AppStateRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(
        alias: Name,
        aliased: Table<AppStateRecord>?,
        parameters: Array<Field<*>?>?,
    ) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(
        alias: Name,
        aliased: Table<AppStateRecord>?,
        where: Condition?,
    ) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.app_state</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.app_state</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.app_state</code> table reference
     */
    constructor() : this(DSL.name("app_state"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AppStateRecord>?, parentPath: InverseForeignKey<out Record, AppStateRecord>?) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        APP_STATE,
        null,
        null,
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AppStatePath :
        AppState,
        Path<AppStateRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, AppStateRecord>?,
            parentPath: InverseForeignKey<out Record, AppStateRecord>?,
        ) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AppStateRecord>) : super(alias, aliased)

        override fun `as`(alias: String): AppStatePath = AppStatePath(DSL.name(alias), this)

        override fun `as`(alias: Name): AppStatePath = AppStatePath(alias, this)

        override fun `as`(alias: Table<*>): AppStatePath = AppStatePath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

    override fun getIdentity(): Identity<AppStateRecord, Long?> = super.getIdentity() as Identity<AppStateRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<AppStateRecord> = APP_STATE_PKEY

    override fun getUniqueKeys(): List<UniqueKey<AppStateRecord>> = listOf(APP_STATE_USER_ID_KEY)

    override fun getReferences(): List<ForeignKey<AppStateRecord, *>> = listOf(APP_STATE__APP_STATE_USER_ID_FKEY)

    private lateinit var _user: UserPath

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    fun user(): UserPath {
        if (!this::_user.isInitialized) {
            _user = UserPath(this, APP_STATE__APP_STATE_USER_ID_FKEY, null)
        }

        return _user
    }

    val user: UserPath
        get(): UserPath = user()

    override fun `as`(alias: String): AppState = AppState(DSL.name(alias), this)

    override fun `as`(alias: Name): AppState = AppState(alias, this)

    override fun `as`(alias: Table<*>): AppState = AppState(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AppState = AppState(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AppState = AppState(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AppState = AppState(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AppState = AppState(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AppState = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AppState = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AppState = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AppState = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
    ): AppState = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg binds: Any?,
    ): AppState = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg parts: QueryPart,
    ): AppState = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AppState = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AppState = where(DSL.notExists(select))
}
