/*
 * This file is generated by jOOQ.
 */
package jooq.tables

import jooq.Public
import jooq.enums.ClusterStatus
import jooq.keys.CLUSTER_PKEY
import jooq.keys.FEED_ITEM__FEED_ITEM_CLUSTER_ID_FKEY
import jooq.tables.FeedItem.FeedItemPath
import jooq.tables.records.ClusterRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime
import kotlin.collections.Collection

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Cluster(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ClusterRecord>?,
    parentPath: InverseForeignKey<out Record, ClusterRecord>?,
    aliased: Table<ClusterRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<ClusterRecord>(
        alias,
        Public.PUBLIC,
        path,
        childPath,
        parentPath,
        aliased,
        parameters,
        DSL.comment(""),
        TableOptions.table(),
        where,
    ) {
    companion object {
        /**
         * The reference instance of <code>public.cluster</code>
         */
        val CLUSTER: Cluster = Cluster()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ClusterRecord> = ClusterRecord::class.java

    /**
     * The column <code>public.cluster.id</code>.
     */
    val ID: TableField<ClusterRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.cluster.label</code>.
     */
    val LABEL: TableField<ClusterRecord, String?> = createField(DSL.name("label"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.cluster.summary</code>.
     */
    val SUMMARY: TableField<ClusterRecord, String?> = createField(DSL.name("summary"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.cluster.status</code>.
     */
    val STATUS: TableField<ClusterRecord, ClusterStatus?> =
        createField(
            DSL.name("status"),
            SQLDataType.VARCHAR
                .nullable(
                    false,
                ).defaultValue(DSL.field(DSL.raw("'PENDING'::cluster_status"), SQLDataType.VARCHAR))
                .asEnumDataType(ClusterStatus::class.java),
            this,
            "",
        )

    /**
     * The column <code>public.cluster.article_count</code>.
     */
    val ARTICLE_COUNT: TableField<ClusterRecord, Int?> =
        createField(DSL.name("article_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.cluster.window_start</code>.
     */
    val WINDOW_START: TableField<ClusterRecord, OffsetDateTime?> =
        createField(DSL.name("window_start"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.cluster.window_end</code>.
     */
    val WINDOW_END: TableField<ClusterRecord, OffsetDateTime?> =
        createField(DSL.name("window_end"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.cluster.created_at</code>.
     */
    val CREATED_AT: TableField<ClusterRecord, OffsetDateTime?> =
        createField(
            DSL.name("created_at"),
            SQLDataType
                .TIMESTAMPWITHTIMEZONE(
                    6,
                ).nullable(false)
                .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this,
            "",
        )

    private constructor(alias: Name, aliased: Table<ClusterRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(
        alias: Name,
        aliased: Table<ClusterRecord>?,
        parameters: Array<Field<*>?>?,
    ) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(
        alias: Name,
        aliased: Table<ClusterRecord>?,
        where: Condition?,
    ) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.cluster</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.cluster</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.cluster</code> table reference
     */
    constructor() : this(DSL.name("cluster"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ClusterRecord>?, parentPath: InverseForeignKey<out Record, ClusterRecord>?) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        CLUSTER,
        null,
        null,
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ClusterPath :
        Cluster,
        Path<ClusterRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ClusterRecord>?,
            parentPath: InverseForeignKey<out Record, ClusterRecord>?,
        ) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ClusterRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ClusterPath = ClusterPath(DSL.name(alias), this)

        override fun `as`(alias: Name): ClusterPath = ClusterPath(alias, this)

        override fun `as`(alias: Table<*>): ClusterPath = ClusterPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

    override fun getIdentity(): Identity<ClusterRecord, Long?> = super.getIdentity() as Identity<ClusterRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<ClusterRecord> = CLUSTER_PKEY

    private lateinit var _feedItem: FeedItemPath

    /**
     * Get the implicit to-many join path to the <code>public.feed_item</code>
     * table
     */
    fun feedItem(): FeedItemPath {
        if (!this::_feedItem.isInitialized) {
            _feedItem = FeedItemPath(this, null, FEED_ITEM__FEED_ITEM_CLUSTER_ID_FKEY.inverseKey)
        }

        return _feedItem
    }

    val feedItem: FeedItemPath
        get(): FeedItemPath = feedItem()

    override fun `as`(alias: String): Cluster = Cluster(DSL.name(alias), this)

    override fun `as`(alias: Name): Cluster = Cluster(alias, this)

    override fun `as`(alias: Table<*>): Cluster = Cluster(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Cluster = Cluster(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Cluster = Cluster(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Cluster = Cluster(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Cluster = Cluster(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Cluster = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Cluster = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Cluster = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Cluster = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
    ): Cluster = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg binds: Any?,
    ): Cluster = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg parts: QueryPart,
    ): Cluster = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Cluster = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Cluster = where(DSL.notExists(select))
}
