/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.tables.SavedItem.SavedItemPath;
import jooq.tables.Source.SourcePath;
import jooq.tables.Summary.SummaryPath;
import jooq.tables.User.UserPath;
import jooq.tables.records.FeedItemRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedItem extends TableImpl<FeedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.feed_item</code>
     */
    public static final FeedItem FEED_ITEM = new FeedItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedItemRecord> getRecordType() {
        return FeedItemRecord.class;
    }

    /**
     * The column <code>public.feed_item.id</code>.
     */
    public final TableField<FeedItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.feed_item.source_id</code>.
     */
    public final TableField<FeedItemRecord, Long> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.feed_item.external_id</code>.
     */
    public final TableField<FeedItemRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.feed_item.title</code>.
     */
    public final TableField<FeedItemRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.feed_item.content</code>.
     */
    public final TableField<FeedItemRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.feed_item.url</code>.
     */
    public final TableField<FeedItemRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.feed_item.thumbnail_url</code>.
     */
    public final TableField<FeedItemRecord, String> THUMBNAIL_URL = createField(DSL.name("thumbnail_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.feed_item.author</code>.
     */
    public final TableField<FeedItemRecord, String> AUTHOR = createField(DSL.name("author"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.feed_item.engagement</code>.
     */
    public final TableField<FeedItemRecord, JSONB> ENGAGEMENT = createField(DSL.name("engagement"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.feed_item.published_at</code>.
     */
    public final TableField<FeedItemRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.feed_item.ingested_at</code>.
     */
    public final TableField<FeedItemRecord, OffsetDateTime> INGESTED_AT = createField(DSL.name("ingested_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private FeedItem(Name alias, Table<FeedItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FeedItem(Name alias, Table<FeedItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    public FeedItem(String alias) {
        this(DSL.name(alias), FEED_ITEM);
    }

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    public FeedItem(Name alias) {
        this(alias, FEED_ITEM);
    }

    /**
     * Create a <code>public.feed_item</code> table reference
     */
    public FeedItem() {
        this(DSL.name("feed_item"), null);
    }

    public <O extends Record> FeedItem(Table<O> path, ForeignKey<O, FeedItemRecord> childPath, InverseForeignKey<O, FeedItemRecord> parentPath) {
        super(path, childPath, parentPath, FEED_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FeedItemPath extends FeedItem implements Path<FeedItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FeedItemPath(Table<O> path, ForeignKey<O, FeedItemRecord> childPath, InverseForeignKey<O, FeedItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FeedItemPath(Name alias, Table<FeedItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FeedItemPath as(String alias) {
            return new FeedItemPath(DSL.name(alias), this);
        }

        @Override
        public FeedItemPath as(Name alias) {
            return new FeedItemPath(alias, this);
        }

        @Override
        public FeedItemPath as(Table<?> alias) {
            return new FeedItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FEED_ITEM_PUBLISHED_AT, Indexes.IDX_FEED_ITEM_SOURCE_PUBLISHED);
    }

    @Override
    public Identity<FeedItemRecord, Long> getIdentity() {
        return (Identity<FeedItemRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FeedItemRecord> getPrimaryKey() {
        return Keys.FEED_ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<FeedItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FEED_ITEM_SOURCE_ID_EXTERNAL_ID_KEY);
    }

    @Override
    public List<ForeignKey<FeedItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY);
    }

    private transient SourcePath _source;

    /**
     * Get the implicit join path to the <code>public.source</code> table.
     */
    public SourcePath source() {
        if (_source == null)
            _source = new SourcePath(this, Keys.FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY, null);

        return _source;
    }

    private transient SavedItemPath _savedItem;

    /**
     * Get the implicit to-many join path to the <code>public.saved_item</code>
     * table
     */
    public SavedItemPath savedItem() {
        if (_savedItem == null)
            _savedItem = new SavedItemPath(this, null, Keys.SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY.getInverseKey());

        return _savedItem;
    }

    private transient SummaryPath _summary;

    /**
     * Get the implicit to-many join path to the <code>public.summary</code>
     * table
     */
    public SummaryPath summary() {
        if (_summary == null)
            _summary = new SummaryPath(this, null, Keys.SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY.getInverseKey());

        return _summary;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.user</code>
     * table
     */
    public UserPath user() {
        return savedItem().user();
    }

    @Override
    public FeedItem as(String alias) {
        return new FeedItem(DSL.name(alias), this);
    }

    @Override
    public FeedItem as(Name alias) {
        return new FeedItem(alias, this);
    }

    @Override
    public FeedItem as(Table<?> alias) {
        return new FeedItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedItem rename(String name) {
        return new FeedItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedItem rename(Name name) {
        return new FeedItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedItem rename(Table<?> name) {
        return new FeedItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem where(Condition condition) {
        return new FeedItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FeedItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FeedItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
