/*
 * This file is generated by jOOQ.
 */
package jooq.tables


import java.time.OffsetDateTime

import jooq.Public
import jooq.keys.FEED_ITEM_CONTENT__FEED_ITEM_CONTENT_FEED_ITEM_ID_FKEY
import jooq.keys.FEED_ITEM_PKEY
import jooq.keys.FEED_ITEM_SOURCE_ID_EXTERNAL_ID_KEY
import jooq.keys.FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY
import jooq.keys.SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY
import jooq.tables.FeedItemContent.FeedItemContentPath
import jooq.tables.SavedItem.SavedItemPath
import jooq.tables.Source.SourcePath
import jooq.tables.User.UserPath
import jooq.tables.records.FeedItemRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FeedItem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FeedItemRecord>?,
    parentPath: InverseForeignKey<out Record, FeedItemRecord>?,
    aliased: Table<FeedItemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FeedItemRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.feed_item</code>
         */
        val FEED_ITEM: FeedItem = FeedItem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FeedItemRecord> = FeedItemRecord::class.java

    /**
     * The column <code>public.feed_item.id</code>.
     */
    val ID: TableField<FeedItemRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.feed_item.source_id</code>.
     */
    val SOURCE_ID: TableField<FeedItemRecord, Long?> = createField(DSL.name("source_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.external_id</code>.
     */
    val EXTERNAL_ID: TableField<FeedItemRecord, String?> = createField(DSL.name("external_id"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.title</code>.
     */
    val TITLE: TableField<FeedItemRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.summary</code>.
     */
    val SUMMARY: TableField<FeedItemRecord, String?> = createField(DSL.name("summary"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.feed_item.url</code>.
     */
    val URL: TableField<FeedItemRecord, String?> = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.thumbnail_url</code>.
     */
    val THUMBNAIL_URL: TableField<FeedItemRecord, String?> = createField(DSL.name("thumbnail_url"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.feed_item.author</code>.
     */
    val AUTHOR: TableField<FeedItemRecord, String?> = createField(DSL.name("author"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.feed_item.engagement</code>.
     */
    val ENGAGEMENT: TableField<FeedItemRecord, JSONB?> = createField(DSL.name("engagement"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.feed_item.published_at</code>.
     */
    val PUBLISHED_AT: TableField<FeedItemRecord, OffsetDateTime?> = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    /**
     * The column <code>public.feed_item.updated_at</code>.
     */
    val UPDATED_AT: TableField<FeedItemRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.feed_item.ingested_at</code>.
     */
    val INGESTED_AT: TableField<FeedItemRecord, OffsetDateTime?> = createField(DSL.name("ingested_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<FeedItemRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FeedItemRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FeedItemRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.feed_item</code> table reference
     */
    constructor(): this(DSL.name("feed_item"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FeedItemRecord>?, parentPath: InverseForeignKey<out Record, FeedItemRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, FEED_ITEM, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FeedItemPath : FeedItem, Path<FeedItemRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FeedItemRecord>?, parentPath: InverseForeignKey<out Record, FeedItemRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<FeedItemRecord>): super(alias, aliased)
        override fun `as`(alias: String): FeedItemPath = FeedItemPath(DSL.name(alias), this)
        override fun `as`(alias: Name): FeedItemPath = FeedItemPath(alias, this)
        override fun `as`(alias: Table<*>): FeedItemPath = FeedItemPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<FeedItemRecord, Long?> = super.getIdentity() as Identity<FeedItemRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<FeedItemRecord> = FEED_ITEM_PKEY
    override fun getUniqueKeys(): List<UniqueKey<FeedItemRecord>> = listOf(FEED_ITEM_SOURCE_ID_EXTERNAL_ID_KEY)
    override fun getReferences(): List<ForeignKey<FeedItemRecord, *>> = listOf(FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY)

    private lateinit var _source: SourcePath

    /**
     * Get the implicit join path to the <code>public.source</code> table.
     */
    fun source(): SourcePath {
        if (!this::_source.isInitialized)
            _source = SourcePath(this, FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY, null)

        return _source;
    }

    val source: SourcePath
        get(): SourcePath = source()

    private lateinit var _feedItemContent: FeedItemContentPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.feed_item_content</code> table
     */
    fun feedItemContent(): FeedItemContentPath {
        if (!this::_feedItemContent.isInitialized)
            _feedItemContent = FeedItemContentPath(this, null, FEED_ITEM_CONTENT__FEED_ITEM_CONTENT_FEED_ITEM_ID_FKEY.inverseKey)

        return _feedItemContent;
    }

    val feedItemContent: FeedItemContentPath
        get(): FeedItemContentPath = feedItemContent()

    private lateinit var _savedItem: SavedItemPath

    /**
     * Get the implicit to-many join path to the <code>public.saved_item</code>
     * table
     */
    fun savedItem(): SavedItemPath {
        if (!this::_savedItem.isInitialized)
            _savedItem = SavedItemPath(this, null, SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY.inverseKey)

        return _savedItem;
    }

    val savedItem: SavedItemPath
        get(): SavedItemPath = savedItem()

    /**
     * Get the implicit many-to-many join path to the <code>public.user</code>
     * table
     */
    val user: UserPath
        get(): UserPath = savedItem().user()
    override fun `as`(alias: String): FeedItem = FeedItem(DSL.name(alias), this)
    override fun `as`(alias: Name): FeedItem = FeedItem(alias, this)
    override fun `as`(alias: Table<*>): FeedItem = FeedItem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FeedItem = FeedItem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FeedItem = FeedItem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FeedItem = FeedItem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FeedItem = FeedItem(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FeedItem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FeedItem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FeedItem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FeedItem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): FeedItem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): FeedItem = where(DSL.notExists(select))
}
