/*
 * This file is generated by jOOQ.
 */
package jooq.tables

import jooq.Public
import jooq.keys.FEED_ITEM_CONTENT_FEED_ITEM_ID_KEY
import jooq.keys.FEED_ITEM_CONTENT_PKEY
import jooq.keys.FEED_ITEM_CONTENT__FEED_ITEM_CONTENT_FEED_ITEM_ID_FKEY
import jooq.tables.FeedItem.FeedItemPath
import jooq.tables.records.FeedItemContentRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FeedItemContent(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FeedItemContentRecord>?,
    parentPath: InverseForeignKey<out Record, FeedItemContentRecord>?,
    aliased: Table<FeedItemContentRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<FeedItemContentRecord>(
        alias,
        Public.PUBLIC,
        path,
        childPath,
        parentPath,
        aliased,
        parameters,
        DSL.comment(""),
        TableOptions.table(),
        where,
    ) {
    companion object {
        /**
         * The reference instance of <code>public.feed_item_content</code>
         */
        val FEED_ITEM_CONTENT: FeedItemContent = FeedItemContent()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FeedItemContentRecord> = FeedItemContentRecord::class.java

    /**
     * The column <code>public.feed_item_content.id</code>.
     */
    val ID: TableField<FeedItemContentRecord, Long?> =
        createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.feed_item_content.feed_item_id</code>.
     */
    val FEED_ITEM_ID: TableField<FeedItemContentRecord, Long?> =
        createField(DSL.name("feed_item_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.feed_item_content.content</code>.
     */
    val CONTENT: TableField<FeedItemContentRecord, String?> = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item_content.ingested_at</code>.
     */
    val INGESTED_AT: TableField<FeedItemContentRecord, OffsetDateTime?> =
        createField(
            DSL.name("ingested_at"),
            SQLDataType
                .TIMESTAMPWITHTIMEZONE(
                    6,
                ).nullable(false)
                .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this,
            "",
        )

    private constructor(alias: Name, aliased: Table<FeedItemContentRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(
        alias: Name,
        aliased: Table<FeedItemContentRecord>?,
        parameters: Array<Field<*>?>?,
    ) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(
        alias: Name,
        aliased: Table<FeedItemContentRecord>?,
        where: Condition?,
    ) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.feed_item_content</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.feed_item_content</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.feed_item_content</code> table reference
     */
    constructor() : this(DSL.name("feed_item_content"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, FeedItemContentRecord>?, parentPath: InverseForeignKey<out Record, FeedItemContentRecord>?) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        FEED_ITEM_CONTENT,
        null,
        null,
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class FeedItemContentPath :
        FeedItemContent,
        Path<FeedItemContentRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, FeedItemContentRecord>?,
            parentPath: InverseForeignKey<out Record, FeedItemContentRecord>?,
        ) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<FeedItemContentRecord>) : super(alias, aliased)

        override fun `as`(alias: String): FeedItemContentPath = FeedItemContentPath(DSL.name(alias), this)

        override fun `as`(alias: Name): FeedItemContentPath = FeedItemContentPath(alias, this)

        override fun `as`(alias: Table<*>): FeedItemContentPath = FeedItemContentPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

    override fun getIdentity(): Identity<FeedItemContentRecord, Long?> = super.getIdentity() as Identity<FeedItemContentRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<FeedItemContentRecord> = FEED_ITEM_CONTENT_PKEY

    override fun getUniqueKeys(): List<UniqueKey<FeedItemContentRecord>> = listOf(FEED_ITEM_CONTENT_FEED_ITEM_ID_KEY)

    override fun getReferences(): List<ForeignKey<FeedItemContentRecord, *>> =
        listOf(FEED_ITEM_CONTENT__FEED_ITEM_CONTENT_FEED_ITEM_ID_FKEY)

    private lateinit var _feedItem: FeedItemPath

    /**
     * Get the implicit join path to the <code>public.feed_item</code> table.
     */
    fun feedItem(): FeedItemPath {
        if (!this::_feedItem.isInitialized) {
            _feedItem = FeedItemPath(this, FEED_ITEM_CONTENT__FEED_ITEM_CONTENT_FEED_ITEM_ID_FKEY, null)
        }

        return _feedItem
    }

    val feedItem: FeedItemPath
        get(): FeedItemPath = feedItem()

    override fun `as`(alias: String): FeedItemContent = FeedItemContent(DSL.name(alias), this)

    override fun `as`(alias: Name): FeedItemContent = FeedItemContent(alias, this)

    override fun `as`(alias: Table<*>): FeedItemContent = FeedItemContent(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FeedItemContent = FeedItemContent(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FeedItemContent = FeedItemContent(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FeedItemContent = FeedItemContent(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FeedItemContent = FeedItemContent(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FeedItemContent = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FeedItemContent = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FeedItemContent = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FeedItemContent = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
    ): FeedItemContent = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg binds: Any?,
    ): FeedItemContent = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg parts: QueryPart,
    ): FeedItemContent = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): FeedItemContent = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): FeedItemContent = where(DSL.notExists(select))
}
