/*
 * This file is generated by jOOQ.
 */
package jooq.tables

import jooq.Public
import jooq.keys.SAVED_ITEM_PKEY
import jooq.keys.SAVED_ITEM_USER_ID_FEED_ITEM_ID_KEY
import jooq.keys.SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY
import jooq.keys.SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY
import jooq.tables.FeedItem.FeedItemPath
import jooq.tables.User.UserPath
import jooq.tables.records.SavedItemRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime
import kotlin.collections.Collection
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SavedItem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SavedItemRecord>?,
    parentPath: InverseForeignKey<out Record, SavedItemRecord>?,
    aliased: Table<SavedItemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?,
) : TableImpl<SavedItemRecord>(
        alias,
        Public.PUBLIC,
        path,
        childPath,
        parentPath,
        aliased,
        parameters,
        DSL.comment(""),
        TableOptions.table(),
        where,
    ) {
    companion object {
        /**
         * The reference instance of <code>public.saved_item</code>
         */
        val SAVED_ITEM: SavedItem = SavedItem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SavedItemRecord> = SavedItemRecord::class.java

    /**
     * The column <code>public.saved_item.id</code>.
     */
    val ID: TableField<SavedItemRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.saved_item.user_id</code>.
     */
    val USER_ID: TableField<SavedItemRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.saved_item.feed_item_id</code>.
     */
    val FEED_ITEM_ID: TableField<SavedItemRecord, Long?> =
        createField(DSL.name("feed_item_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.saved_item.saved_at</code>.
     */
    val SAVED_AT: TableField<SavedItemRecord, OffsetDateTime?> =
        createField(
            DSL.name("saved_at"),
            SQLDataType
                .TIMESTAMPWITHTIMEZONE(
                    6,
                ).nullable(false)
                .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this,
            "",
        )

    private constructor(alias: Name, aliased: Table<SavedItemRecord>?) : this(alias, null, null, null, aliased, null, null)
    private constructor(
        alias: Name,
        aliased: Table<SavedItemRecord>?,
        parameters: Array<Field<*>?>?,
    ) : this(alias, null, null, null, aliased, parameters, null)
    private constructor(
        alias: Name,
        aliased: Table<SavedItemRecord>?,
        where: Condition?,
    ) : this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.saved_item</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.saved_item</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.saved_item</code> table reference
     */
    constructor() : this(DSL.name("saved_item"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SavedItemRecord>?, parentPath: InverseForeignKey<out Record, SavedItemRecord>?) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        SAVED_ITEM,
        null,
        null,
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class SavedItemPath :
        SavedItem,
        Path<SavedItemRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, SavedItemRecord>?,
            parentPath: InverseForeignKey<out Record, SavedItemRecord>?,
        ) : super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SavedItemRecord>) : super(alias, aliased)

        override fun `as`(alias: String): SavedItemPath = SavedItemPath(DSL.name(alias), this)

        override fun `as`(alias: Name): SavedItemPath = SavedItemPath(alias, this)

        override fun `as`(alias: Table<*>): SavedItemPath = SavedItemPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

    override fun getIdentity(): Identity<SavedItemRecord, Long?> = super.getIdentity() as Identity<SavedItemRecord, Long?>

    override fun getPrimaryKey(): UniqueKey<SavedItemRecord> = SAVED_ITEM_PKEY

    override fun getUniqueKeys(): List<UniqueKey<SavedItemRecord>> = listOf(SAVED_ITEM_USER_ID_FEED_ITEM_ID_KEY)

    override fun getReferences(): List<ForeignKey<SavedItemRecord, *>> =
        listOf(SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY, SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY)

    private lateinit var _feedItem: FeedItemPath

    /**
     * Get the implicit join path to the <code>public.feed_item</code> table.
     */
    fun feedItem(): FeedItemPath {
        if (!this::_feedItem.isInitialized) {
            _feedItem = FeedItemPath(this, SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY, null)
        }

        return _feedItem
    }

    val feedItem: FeedItemPath
        get(): FeedItemPath = feedItem()

    private lateinit var _user: UserPath

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    fun user(): UserPath {
        if (!this::_user.isInitialized) {
            _user = UserPath(this, SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY, null)
        }

        return _user
    }

    val user: UserPath
        get(): UserPath = user()

    override fun `as`(alias: String): SavedItem = SavedItem(DSL.name(alias), this)

    override fun `as`(alias: Name): SavedItem = SavedItem(alias, this)

    override fun `as`(alias: Table<*>): SavedItem = SavedItem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SavedItem = SavedItem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SavedItem = SavedItem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SavedItem = SavedItem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SavedItem = SavedItem(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SavedItem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SavedItem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SavedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SavedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
    ): SavedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg binds: Any?,
    ): SavedItem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(
        @Stringly.SQL condition: String,
        vararg parts: QueryPart,
    ): SavedItem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SavedItem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SavedItem = where(DSL.notExists(select))
}
