/*
 * This file is generated by jOOQ.
 */
package jooq.tables


import java.time.OffsetDateTime

import jooq.Public
import jooq.enums.SourceType
import jooq.keys.FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY
import jooq.keys.SOURCE_PKEY
import jooq.keys.SOURCE_URL_KEY
import jooq.tables.FeedItem.FeedItemPath
import jooq.tables.records.SourceRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Source(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SourceRecord>?,
    parentPath: InverseForeignKey<out Record, SourceRecord>?,
    aliased: Table<SourceRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SourceRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.source</code>
         */
        val SOURCE: Source = Source()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SourceRecord> = SourceRecord::class.java

    /**
     * The column <code>public.source.id</code>.
     */
    val ID: TableField<SourceRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.source.type</code>.
     */
    val TYPE: TableField<SourceRecord, SourceType?> = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(SourceType::class.java), this, "")

    /**
     * The column <code>public.source.name</code>.
     */
    val NAME: TableField<SourceRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.source.url</code>.
     */
    val URL: TableField<SourceRecord, String?> = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.source.enabled</code>.
     */
    val ENABLED: TableField<SourceRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.source.created_at</code>.
     */
    val CREATED_AT: TableField<SourceRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<SourceRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SourceRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SourceRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.source</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.source</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.source</code> table reference
     */
    constructor(): this(DSL.name("source"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SourceRecord>?, parentPath: InverseForeignKey<out Record, SourceRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SOURCE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class SourcePath : Source, Path<SourceRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SourceRecord>?, parentPath: InverseForeignKey<out Record, SourceRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SourceRecord>): super(alias, aliased)
        override fun `as`(alias: String): SourcePath = SourcePath(DSL.name(alias), this)
        override fun `as`(alias: Name): SourcePath = SourcePath(alias, this)
        override fun `as`(alias: Table<*>): SourcePath = SourcePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<SourceRecord, Long?> = super.getIdentity() as Identity<SourceRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<SourceRecord> = SOURCE_PKEY
    override fun getUniqueKeys(): List<UniqueKey<SourceRecord>> = listOf(SOURCE_URL_KEY)

    private lateinit var _feedItem: FeedItemPath

    /**
     * Get the implicit to-many join path to the <code>public.feed_item</code>
     * table
     */
    fun feedItem(): FeedItemPath {
        if (!this::_feedItem.isInitialized)
            _feedItem = FeedItemPath(this, null, FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY.inverseKey)

        return _feedItem;
    }

    val feedItem: FeedItemPath
        get(): FeedItemPath = feedItem()
    override fun `as`(alias: String): Source = Source(DSL.name(alias), this)
    override fun `as`(alias: Name): Source = Source(alias, this)
    override fun `as`(alias: Table<*>): Source = Source(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Source = Source(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Source = Source(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Source = Source(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Source = Source(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Source = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Source = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Source = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Source = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Source = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Source = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Source = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Source = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Source = where(DSL.notExists(select))
}
