/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.Keys;
import jooq.Public;
import jooq.tables.FeedItem.FeedItemPath;
import jooq.tables.records.SummaryRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Summary extends TableImpl<SummaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.summary</code>
     */
    public static final Summary SUMMARY = new Summary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SummaryRecord> getRecordType() {
        return SummaryRecord.class;
    }

    /**
     * The column <code>public.summary.id</code>.
     */
    public final TableField<SummaryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.summary.feed_item_id</code>.
     */
    public final TableField<SummaryRecord, Long> FEED_ITEM_ID = createField(DSL.name("feed_item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.summary.content</code>.
     */
    public final TableField<SummaryRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.summary.model</code>.
     */
    public final TableField<SummaryRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.summary.generated_at</code>.
     */
    public final TableField<SummaryRecord, OffsetDateTime> GENERATED_AT = createField(DSL.name("generated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Summary(Name alias, Table<SummaryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Summary(Name alias, Table<SummaryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.summary</code> table reference
     */
    public Summary(String alias) {
        this(DSL.name(alias), SUMMARY);
    }

    /**
     * Create an aliased <code>public.summary</code> table reference
     */
    public Summary(Name alias) {
        this(alias, SUMMARY);
    }

    /**
     * Create a <code>public.summary</code> table reference
     */
    public Summary() {
        this(DSL.name("summary"), null);
    }

    public <O extends Record> Summary(Table<O> path, ForeignKey<O, SummaryRecord> childPath, InverseForeignKey<O, SummaryRecord> parentPath) {
        super(path, childPath, parentPath, SUMMARY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SummaryPath extends Summary implements Path<SummaryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SummaryPath(Table<O> path, ForeignKey<O, SummaryRecord> childPath, InverseForeignKey<O, SummaryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SummaryPath(Name alias, Table<SummaryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SummaryPath as(String alias) {
            return new SummaryPath(DSL.name(alias), this);
        }

        @Override
        public SummaryPath as(Name alias) {
            return new SummaryPath(alias, this);
        }

        @Override
        public SummaryPath as(Table<?> alias) {
            return new SummaryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SummaryRecord, Long> getIdentity() {
        return (Identity<SummaryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SummaryRecord> getPrimaryKey() {
        return Keys.SUMMARY_PKEY;
    }

    @Override
    public List<UniqueKey<SummaryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SUMMARY_FEED_ITEM_ID_KEY);
    }

    @Override
    public List<ForeignKey<SummaryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY);
    }

    private transient FeedItemPath _feedItem;

    /**
     * Get the implicit join path to the <code>public.feed_item</code> table.
     */
    public FeedItemPath feedItem() {
        if (_feedItem == null)
            _feedItem = new FeedItemPath(this, Keys.SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY, null);

        return _feedItem;
    }

    @Override
    public Summary as(String alias) {
        return new Summary(DSL.name(alias), this);
    }

    @Override
    public Summary as(Name alias) {
        return new Summary(alias, this);
    }

    @Override
    public Summary as(Table<?> alias) {
        return new Summary(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Summary rename(String name) {
        return new Summary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Summary rename(Name name) {
        return new Summary(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Summary rename(Table<?> name) {
        return new Summary(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary where(Condition condition) {
        return new Summary(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Summary where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Summary where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Summary where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Summary where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Summary whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
