/*
 * This file is generated by jOOQ.
 */
package jooq.tables


import java.time.OffsetDateTime

import jooq.Public
import jooq.keys.SUMMARY_FEED_ITEM_ID_KEY
import jooq.keys.SUMMARY_PKEY
import jooq.keys.SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY
import jooq.tables.FeedItem.FeedItemPath
import jooq.tables.records.SummaryRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Summary(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SummaryRecord>?,
    parentPath: InverseForeignKey<out Record, SummaryRecord>?,
    aliased: Table<SummaryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SummaryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.summary</code>
         */
        val SUMMARY: Summary = Summary()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SummaryRecord> = SummaryRecord::class.java

    /**
     * The column <code>public.summary.id</code>.
     */
    val ID: TableField<SummaryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.summary.feed_item_id</code>.
     */
    val FEED_ITEM_ID: TableField<SummaryRecord, Long?> = createField(DSL.name("feed_item_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.summary.content</code>.
     */
    val CONTENT: TableField<SummaryRecord, String?> = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.summary.generated_at</code>.
     */
    val GENERATED_AT: TableField<SummaryRecord, OffsetDateTime?> = createField(DSL.name("generated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<SummaryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SummaryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SummaryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.summary</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.summary</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.summary</code> table reference
     */
    constructor(): this(DSL.name("summary"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SummaryRecord>?, parentPath: InverseForeignKey<out Record, SummaryRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SUMMARY, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class SummaryPath : Summary, Path<SummaryRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SummaryRecord>?, parentPath: InverseForeignKey<out Record, SummaryRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SummaryRecord>): super(alias, aliased)
        override fun `as`(alias: String): SummaryPath = SummaryPath(DSL.name(alias), this)
        override fun `as`(alias: Name): SummaryPath = SummaryPath(alias, this)
        override fun `as`(alias: Table<*>): SummaryPath = SummaryPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<SummaryRecord, Long?> = super.getIdentity() as Identity<SummaryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<SummaryRecord> = SUMMARY_PKEY
    override fun getUniqueKeys(): List<UniqueKey<SummaryRecord>> = listOf(SUMMARY_FEED_ITEM_ID_KEY)
    override fun getReferences(): List<ForeignKey<SummaryRecord, *>> = listOf(SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY)

    private lateinit var _feedItem: FeedItemPath

    /**
     * Get the implicit join path to the <code>public.feed_item</code> table.
     */
    fun feedItem(): FeedItemPath {
        if (!this::_feedItem.isInitialized)
            _feedItem = FeedItemPath(this, SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY, null)

        return _feedItem;
    }

    val feedItem: FeedItemPath
        get(): FeedItemPath = feedItem()
    override fun `as`(alias: String): Summary = Summary(DSL.name(alias), this)
    override fun `as`(alias: Name): Summary = Summary(alias, this)
    override fun `as`(alias: Table<*>): Summary = Summary(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Summary = Summary(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Summary = Summary(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Summary = Summary(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Summary = Summary(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Summary = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Summary = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Summary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Summary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Summary = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Summary = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Summary = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Summary = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Summary = where(DSL.notExists(select))
}
