/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.OffsetDateTime;

import jooq.enums.SourceType;
import jooq.tables.Source;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SourceRecord extends UpdatableRecordImpl<SourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.source.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.source.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.source.type</code>.
     */
    public void setType(SourceType value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.source.type</code>.
     */
    public SourceType getType() {
        return (SourceType) get(1);
    }

    /**
     * Setter for <code>public.source.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.source.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.source.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.source.url</code>.
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.source.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.source.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.source.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.source.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceRecord
     */
    public SourceRecord() {
        super(Source.SOURCE);
    }

    /**
     * Create a detached, initialised SourceRecord
     */
    public SourceRecord(Long id, SourceType type, String name, String url, Boolean enabled, OffsetDateTime createdAt) {
        super(Source.SOURCE);

        setId(id);
        setType(type);
        setName(name);
        setUrl(url);
        setEnabled(enabled);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
