/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.OffsetDateTime;

import jooq.tables.Summary;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SummaryRecord extends UpdatableRecordImpl<SummaryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.summary.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.summary.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.summary.feed_item_id</code>.
     */
    public void setFeedItemId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.summary.feed_item_id</code>.
     */
    public Long getFeedItemId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.summary.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.summary.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.summary.model</code>.
     */
    public void setModel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.summary.model</code>.
     */
    public String getModel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.summary.generated_at</code>.
     */
    public void setGeneratedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.summary.generated_at</code>.
     */
    public OffsetDateTime getGeneratedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SummaryRecord
     */
    public SummaryRecord() {
        super(Summary.SUMMARY);
    }

    /**
     * Create a detached, initialised SummaryRecord
     */
    public SummaryRecord(Long id, Long feedItemId, String content, String model, OffsetDateTime generatedAt) {
        super(Summary.SUMMARY);

        setId(id);
        setFeedItemId(feedItemId);
        setContent(content);
        setModel(model);
        setGeneratedAt(generatedAt);
        resetChangedOnNotNull();
    }
}
