/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.Indexes;
import jooq.Keys;
import jooq.Public;
import jooq.tables.FeedItem.FeedItemPath;
import jooq.tables.User.UserPath;
import jooq.tables.records.SavedItemRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SavedItem extends TableImpl<SavedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.saved_item</code>
     */
    public static final SavedItem SAVED_ITEM = new SavedItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SavedItemRecord> getRecordType() {
        return SavedItemRecord.class;
    }

    /**
     * The column <code>public.saved_item.id</code>.
     */
    public final TableField<SavedItemRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.saved_item.user_id</code>.
     */
    public final TableField<SavedItemRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.saved_item.feed_item_id</code>.
     */
    public final TableField<SavedItemRecord, Long> FEED_ITEM_ID = createField(DSL.name("feed_item_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.saved_item.saved_at</code>.
     */
    public final TableField<SavedItemRecord, OffsetDateTime> SAVED_AT = createField(DSL.name("saved_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private SavedItem(Name alias, Table<SavedItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SavedItem(Name alias, Table<SavedItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.saved_item</code> table reference
     */
    public SavedItem(String alias) {
        this(DSL.name(alias), SAVED_ITEM);
    }

    /**
     * Create an aliased <code>public.saved_item</code> table reference
     */
    public SavedItem(Name alias) {
        this(alias, SAVED_ITEM);
    }

    /**
     * Create a <code>public.saved_item</code> table reference
     */
    public SavedItem() {
        this(DSL.name("saved_item"), null);
    }

    public <O extends Record> SavedItem(Table<O> path, ForeignKey<O, SavedItemRecord> childPath, InverseForeignKey<O, SavedItemRecord> parentPath) {
        super(path, childPath, parentPath, SAVED_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SavedItemPath extends SavedItem implements Path<SavedItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SavedItemPath(Table<O> path, ForeignKey<O, SavedItemRecord> childPath, InverseForeignKey<O, SavedItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SavedItemPath(Name alias, Table<SavedItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SavedItemPath as(String alias) {
            return new SavedItemPath(DSL.name(alias), this);
        }

        @Override
        public SavedItemPath as(Name alias) {
            return new SavedItemPath(alias, this);
        }

        @Override
        public SavedItemPath as(Table<?> alias) {
            return new SavedItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SAVED_ITEM_USER_SAVED_AT);
    }

    @Override
    public Identity<SavedItemRecord, Long> getIdentity() {
        return (Identity<SavedItemRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SavedItemRecord> getPrimaryKey() {
        return Keys.SAVED_ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<SavedItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SAVED_ITEM_USER_ID_FEED_ITEM_ID_KEY);
    }

    @Override
    public List<ForeignKey<SavedItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY, Keys.SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY);
    }

    private transient FeedItemPath _feedItem;

    /**
     * Get the implicit join path to the <code>public.feed_item</code> table.
     */
    public FeedItemPath feedItem() {
        if (_feedItem == null)
            _feedItem = new FeedItemPath(this, Keys.SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY, null);

        return _feedItem;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY, null);

        return _user;
    }

    @Override
    public SavedItem as(String alias) {
        return new SavedItem(DSL.name(alias), this);
    }

    @Override
    public SavedItem as(Name alias) {
        return new SavedItem(alias, this);
    }

    @Override
    public SavedItem as(Table<?> alias) {
        return new SavedItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SavedItem rename(String name) {
        return new SavedItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SavedItem rename(Name name) {
        return new SavedItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SavedItem rename(Table<?> name) {
        return new SavedItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem where(Condition condition) {
        return new SavedItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SavedItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SavedItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SavedItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SavedItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SavedItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
