/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.OffsetDateTime;

import jooq.tables.AppState;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppStateRecord extends UpdatableRecordImpl<AppStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.app_state.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_state.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.app_state.last_visited_at</code>.
     */
    public void setLastVisitedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_state.last_visited_at</code>.
     */
    public OffsetDateTime getLastVisitedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.app_state.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_state.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppStateRecord
     */
    public AppStateRecord() {
        super(AppState.APP_STATE);
    }

    /**
     * Create a detached, initialised AppStateRecord
     */
    public AppStateRecord(Long id, Long userId, OffsetDateTime lastVisitedAt, OffsetDateTime updatedAt) {
        super(AppState.APP_STATE);

        setId(id);
        setUserId(userId);
        setLastVisitedAt(lastVisitedAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
