/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.OffsetDateTime

import jooq.enums.ClusterStatus
import jooq.tables.Cluster

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ClusterRecord() : UpdatableRecordImpl<ClusterRecord>(Cluster.CLUSTER) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var label: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var summary: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var status: ClusterStatus?
        set(value): Unit = set(3, value)
        get(): ClusterStatus? = get(3) as ClusterStatus?

    open var articleCount: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var windowStart: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var windowEnd: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ClusterRecord
     */
    constructor(id: Long? = null, label: String? = null, summary: String? = null, status: ClusterStatus? = null, articleCount: Int? = null, windowStart: OffsetDateTime? = null, windowEnd: OffsetDateTime? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.label = label
        this.summary = summary
        this.status = status
        this.articleCount = articleCount
        this.windowStart = windowStart
        this.windowEnd = windowEnd
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
