/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records

import jooq.tables.Embedding
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EmbeddingRecord() : UpdatableRecordImpl<EmbeddingRecord>(Embedding.EMBEDDING) {
    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var feedItemId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var model: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var vector: Array<Float?>?
        set(value): Unit = set(3, value)
        get(): Array<Float?>? = get(3) as Array<Float?>?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised EmbeddingRecord
     */
    constructor(
        id: Long? = null,
        feedItemId: Long? = null,
        model: String? = null,
        vector: Array<Float?>? = null,
        createdAt: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.feedItemId = feedItemId
        this.model = model
        this.vector = vector
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
