/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.OffsetDateTime;

import jooq.tables.FeedItem;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FeedItemRecord extends UpdatableRecordImpl<FeedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.feed_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.feed_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.feed_item.source_id</code>.
     */
    public void setSourceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.feed_item.source_id</code>.
     */
    public Long getSourceId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.feed_item.external_id</code>.
     */
    public void setExternalId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.feed_item.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.feed_item.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.feed_item.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.feed_item.content</code>.
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.feed_item.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.feed_item.url</code>.
     */
    public void setUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.feed_item.url</code>.
     */
    public String getUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.feed_item.thumbnail_url</code>.
     */
    public void setThumbnailUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.feed_item.thumbnail_url</code>.
     */
    public String getThumbnailUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.feed_item.author</code>.
     */
    public void setAuthor(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.feed_item.author</code>.
     */
    public String getAuthor() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.feed_item.engagement</code>.
     */
    public void setEngagement(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.feed_item.engagement</code>.
     */
    public JSONB getEngagement() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.feed_item.published_at</code>.
     */
    public void setPublishedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.feed_item.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.feed_item.ingested_at</code>.
     */
    public void setIngestedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.feed_item.ingested_at</code>.
     */
    public OffsetDateTime getIngestedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedItemRecord
     */
    public FeedItemRecord() {
        super(FeedItem.FEED_ITEM);
    }

    /**
     * Create a detached, initialised FeedItemRecord
     */
    public FeedItemRecord(Long id, Long sourceId, String externalId, String title, String content, String url, String thumbnailUrl, String author, JSONB engagement, OffsetDateTime publishedAt, OffsetDateTime ingestedAt) {
        super(FeedItem.FEED_ITEM);

        setId(id);
        setSourceId(sourceId);
        setExternalId(externalId);
        setTitle(title);
        setContent(content);
        setUrl(url);
        setThumbnailUrl(thumbnailUrl);
        setAuthor(author);
        setEngagement(engagement);
        setPublishedAt(publishedAt);
        setIngestedAt(ingestedAt);
        resetChangedOnNotNull();
    }
}
