/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.OffsetDateTime

import jooq.tables.FeedItem

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FeedItemRecord() : UpdatableRecordImpl<FeedItemRecord>(FeedItem.FEED_ITEM) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var sourceId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var externalId: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var title: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var content: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var url: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var thumbnailUrl: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var author: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var engagement: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var publishedAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var ingestedAt: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised FeedItemRecord
     */
    constructor(id: Long? = null, sourceId: Long? = null, externalId: String? = null, title: String? = null, content: String? = null, url: String? = null, thumbnailUrl: String? = null, author: String? = null, engagement: JSONB? = null, publishedAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, ingestedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.sourceId = sourceId
        this.externalId = externalId
        this.title = title
        this.content = content
        this.url = url
        this.thumbnailUrl = thumbnailUrl
        this.author = author
        this.engagement = engagement
        this.publishedAt = publishedAt
        this.updatedAt = updatedAt
        this.ingestedAt = ingestedAt
        resetChangedOnNotNull()
    }
}
