/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records

import jooq.tables.FeedItemContent
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FeedItemContentRecord() : UpdatableRecordImpl<FeedItemContentRecord>(FeedItemContent.FEED_ITEM_CONTENT) {
    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var feedItemId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var content: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var ingestedAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised FeedItemContentRecord
     */
    constructor(id: Long? = null, feedItemId: Long? = null, content: String? = null, ingestedAt: OffsetDateTime? = null) : this() {
        this.id = id
        this.feedItemId = feedItemId
        this.content = content
        this.ingestedAt = ingestedAt
        resetChangedOnNotNull()
    }
}
