/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records

import jooq.tables.SavedItem
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SavedItemRecord() : UpdatableRecordImpl<SavedItemRecord>(SavedItem.SAVED_ITEM) {
    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var userId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var feedItemId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var savedAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised SavedItemRecord
     */
    constructor(id: Long? = null, userId: Long? = null, feedItemId: Long? = null, savedAt: OffsetDateTime? = null) : this() {
        this.id = id
        this.userId = userId
        this.feedItemId = feedItemId
        this.savedAt = savedAt
        resetChangedOnNotNull()
    }
}
