/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.OffsetDateTime;

import jooq.tables.SavedItem;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SavedItemRecord extends UpdatableRecordImpl<SavedItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.saved_item.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.saved_item.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.saved_item.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.saved_item.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.saved_item.feed_item_id</code>.
     */
    public void setFeedItemId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.saved_item.feed_item_id</code>.
     */
    public Long getFeedItemId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.saved_item.saved_at</code>.
     */
    public void setSavedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.saved_item.saved_at</code>.
     */
    public OffsetDateTime getSavedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SavedItemRecord
     */
    public SavedItemRecord() {
        super(SavedItem.SAVED_ITEM);
    }

    /**
     * Create a detached, initialised SavedItemRecord
     */
    public SavedItemRecord(Long id, Long userId, Long feedItemId, OffsetDateTime savedAt) {
        super(SavedItem.SAVED_ITEM);

        setId(id);
        setUserId(userId);
        setFeedItemId(feedItemId);
        setSavedAt(savedAt);
        resetChangedOnNotNull();
    }
}
