/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.OffsetDateTime

import jooq.enums.SourceType
import jooq.tables.Source

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SourceRecord() : UpdatableRecordImpl<SourceRecord>(Source.SOURCE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var type: SourceType?
        set(value): Unit = set(1, value)
        get(): SourceType? = get(1) as SourceType?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var url: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var homepage: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var enabled: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised SourceRecord
     */
    constructor(id: Long? = null, type: SourceType? = null, name: String? = null, url: String? = null, homepage: String? = null, enabled: Boolean? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.type = type
        this.name = name
        this.url = url
        this.homepage = homepage
        this.enabled = enabled
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
