/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.OffsetDateTime

import jooq.tables.Summary

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SummaryRecord() : UpdatableRecordImpl<SummaryRecord>(Summary.SUMMARY) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var feedItemId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var content: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var generatedAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised SummaryRecord
     */
    constructor(id: Long? = null, feedItemId: Long? = null, content: String? = null, generatedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.feedItemId = feedItemId
        this.content = content
        this.generatedAt = generatedAt
        resetChangedOnNotNull()
    }
}
