/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.OffsetDateTime

import jooq.tables.SystemState

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SystemStateRecord() : UpdatableRecordImpl<SystemStateRecord>(SystemState.SYSTEM_STATE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var lastClusteredAt: OffsetDateTime?
        set(value): Unit = set(1, value)
        get(): OffsetDateTime? = get(1) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised SystemStateRecord
     */
    constructor(id: Long? = null, lastClusteredAt: OffsetDateTime? = null): this() {
        this.id = id
        this.lastClusteredAt = lastClusteredAt
        resetChangedOnNotNull()
    }
}
