/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records

import jooq.tables.User
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UserRecord() : UpdatableRecordImpl<UserRecord>(User.USER) {
    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var email: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var passwordHash: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised UserRecord
     */
    constructor(id: Long? = null, email: String? = null, passwordHash: String? = null, createdAt: OffsetDateTime? = null) : this() {
        this.id = id
        this.email = email
        this.passwordHash = passwordHash
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
