/*
 * This file is generated by jOOQ.
 */
package jooq.enums;


import jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum SourceType implements EnumType {

    NEWS("NEWS"),

    REDDIT("REDDIT"),

    TWITTER("TWITTER");

    private final String literal;

    private SourceType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "source_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static SourceType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(SourceType.class, literal);
    }
}
