/*
 * This file is generated by jOOQ.
 */
package jooq.keys


import jooq.tables.Tweets
import jooq.tables.records.TweetsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TWEETS_PKEY: UniqueKey<TweetsRecord> = Internal.createUniqueKey(Tweets.TWEETS, DSL.name("tweets_pkey"), arrayOf(Tweets.TWEETS.ID), true)
