/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.FeedItem;
import jooq.tables.SavedItem;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_FEED_ITEM_PUBLISHED_AT = Internal.createIndex(DSL.name("idx_feed_item_published_at"), FeedItem.FEED_ITEM, new OrderField[] { FeedItem.FEED_ITEM.PUBLISHED_AT.desc() }, false);
    public static final Index IDX_FEED_ITEM_SOURCE_PUBLISHED = Internal.createIndex(DSL.name("idx_feed_item_source_published"), FeedItem.FEED_ITEM, new OrderField[] { FeedItem.FEED_ITEM.SOURCE_ID, FeedItem.FEED_ITEM.PUBLISHED_AT.desc() }, false);
    public static final Index IDX_SAVED_ITEM_USER_SAVED_AT = Internal.createIndex(DSL.name("idx_saved_item_user_saved_at"), SavedItem.SAVED_ITEM, new OrderField[] { SavedItem.SAVED_ITEM.USER_ID, SavedItem.SAVED_ITEM.SAVED_AT.desc() }, false);
}
