/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.AppState;
import jooq.tables.FeedItem;
import jooq.tables.SavedItem;
import jooq.tables.Source;
import jooq.tables.Summary;
import jooq.tables.User;
import jooq.tables.records.AppStateRecord;
import jooq.tables.records.FeedItemRecord;
import jooq.tables.records.SavedItemRecord;
import jooq.tables.records.SourceRecord;
import jooq.tables.records.SummaryRecord;
import jooq.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppStateRecord> APP_STATE_PKEY = Internal.createUniqueKey(AppState.APP_STATE, DSL.name("app_state_pkey"), new TableField[] { AppState.APP_STATE.ID }, true);
    public static final UniqueKey<AppStateRecord> APP_STATE_USER_ID_KEY = Internal.createUniqueKey(AppState.APP_STATE, DSL.name("app_state_user_id_key"), new TableField[] { AppState.APP_STATE.USER_ID }, true);
    public static final UniqueKey<FeedItemRecord> FEED_ITEM_PKEY = Internal.createUniqueKey(FeedItem.FEED_ITEM, DSL.name("feed_item_pkey"), new TableField[] { FeedItem.FEED_ITEM.ID }, true);
    public static final UniqueKey<FeedItemRecord> FEED_ITEM_SOURCE_ID_EXTERNAL_ID_KEY = Internal.createUniqueKey(FeedItem.FEED_ITEM, DSL.name("feed_item_source_id_external_id_key"), new TableField[] { FeedItem.FEED_ITEM.SOURCE_ID, FeedItem.FEED_ITEM.EXTERNAL_ID }, true);
    public static final UniqueKey<SavedItemRecord> SAVED_ITEM_PKEY = Internal.createUniqueKey(SavedItem.SAVED_ITEM, DSL.name("saved_item_pkey"), new TableField[] { SavedItem.SAVED_ITEM.ID }, true);
    public static final UniqueKey<SavedItemRecord> SAVED_ITEM_USER_ID_FEED_ITEM_ID_KEY = Internal.createUniqueKey(SavedItem.SAVED_ITEM, DSL.name("saved_item_user_id_feed_item_id_key"), new TableField[] { SavedItem.SAVED_ITEM.USER_ID, SavedItem.SAVED_ITEM.FEED_ITEM_ID }, true);
    public static final UniqueKey<SourceRecord> SOURCE_PKEY = Internal.createUniqueKey(Source.SOURCE, DSL.name("source_pkey"), new TableField[] { Source.SOURCE.ID }, true);
    public static final UniqueKey<SourceRecord> SOURCE_URL_KEY = Internal.createUniqueKey(Source.SOURCE, DSL.name("source_url_key"), new TableField[] { Source.SOURCE.URL }, true);
    public static final UniqueKey<SummaryRecord> SUMMARY_FEED_ITEM_ID_KEY = Internal.createUniqueKey(Summary.SUMMARY, DSL.name("summary_feed_item_id_key"), new TableField[] { Summary.SUMMARY.FEED_ITEM_ID }, true);
    public static final UniqueKey<SummaryRecord> SUMMARY_PKEY = Internal.createUniqueKey(Summary.SUMMARY, DSL.name("summary_pkey"), new TableField[] { Summary.SUMMARY.ID }, true);
    public static final UniqueKey<UserRecord> USER_EMAIL_KEY = Internal.createUniqueKey(User.USER, DSL.name("user_email_key"), new TableField[] { User.USER.EMAIL }, true);
    public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), new TableField[] { User.USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppStateRecord, UserRecord> APP_STATE__APP_STATE_USER_ID_FKEY = Internal.createForeignKey(AppState.APP_STATE, DSL.name("app_state_user_id_fkey"), new TableField[] { AppState.APP_STATE.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true);
    public static final ForeignKey<FeedItemRecord, SourceRecord> FEED_ITEM__FEED_ITEM_SOURCE_ID_FKEY = Internal.createForeignKey(FeedItem.FEED_ITEM, DSL.name("feed_item_source_id_fkey"), new TableField[] { FeedItem.FEED_ITEM.SOURCE_ID }, Keys.SOURCE_PKEY, new TableField[] { Source.SOURCE.ID }, true);
    public static final ForeignKey<SavedItemRecord, FeedItemRecord> SAVED_ITEM__SAVED_ITEM_FEED_ITEM_ID_FKEY = Internal.createForeignKey(SavedItem.SAVED_ITEM, DSL.name("saved_item_feed_item_id_fkey"), new TableField[] { SavedItem.SAVED_ITEM.FEED_ITEM_ID }, Keys.FEED_ITEM_PKEY, new TableField[] { FeedItem.FEED_ITEM.ID }, true);
    public static final ForeignKey<SavedItemRecord, UserRecord> SAVED_ITEM__SAVED_ITEM_USER_ID_FKEY = Internal.createForeignKey(SavedItem.SAVED_ITEM, DSL.name("saved_item_user_id_fkey"), new TableField[] { SavedItem.SAVED_ITEM.USER_ID }, Keys.USER_PKEY, new TableField[] { User.USER.ID }, true);
    public static final ForeignKey<SummaryRecord, FeedItemRecord> SUMMARY__SUMMARY_FEED_ITEM_ID_FKEY = Internal.createForeignKey(Summary.SUMMARY, DSL.name("summary_feed_item_id_fkey"), new TableField[] { Summary.SUMMARY.FEED_ITEM_ID }, Keys.FEED_ITEM_PKEY, new TableField[] { FeedItem.FEED_ITEM.ID }, true);
}
