/*
 * This file is generated by jOOQ.
 */
package jooq


import jooq.tables.AppState
import jooq.tables.FeedItem
import jooq.tables.FeedItemContent
import jooq.tables.SavedItem
import jooq.tables.Source
import jooq.tables.User

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.app_state</code>.
     */
    val APP_STATE: AppState get() = AppState.APP_STATE

    /**
     * The table <code>public.feed_item</code>.
     */
    val FEED_ITEM: FeedItem get() = FeedItem.FEED_ITEM

    /**
     * The table <code>public.feed_item_content</code>.
     */
    val FEED_ITEM_CONTENT: FeedItemContent get() = FeedItemContent.FEED_ITEM_CONTENT

    /**
     * The table <code>public.saved_item</code>.
     */
    val SAVED_ITEM: SavedItem get() = SavedItem.SAVED_ITEM

    /**
     * The table <code>public.source</code>.
     */
    val SOURCE: Source get() = Source.SOURCE

    /**
     * The table <code>public.user</code>.
     */
    val USER: User get() = User.USER

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AppState.APP_STATE,
        FeedItem.FEED_ITEM,
        FeedItemContent.FEED_ITEM_CONTENT,
        SavedItem.SAVED_ITEM,
        Source.SOURCE,
        User.USER
    )
}
