/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.AppState;
import jooq.tables.FeedItem;
import jooq.tables.SavedItem;
import jooq.tables.Source;
import jooq.tables.Summary;
import jooq.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_state</code>.
     */
    public final AppState APP_STATE = AppState.APP_STATE;

    /**
     * The table <code>public.feed_item</code>.
     */
    public final FeedItem FEED_ITEM = FeedItem.FEED_ITEM;

    /**
     * The table <code>public.saved_item</code>.
     */
    public final SavedItem SAVED_ITEM = SavedItem.SAVED_ITEM;

    /**
     * The table <code>public.source</code>.
     */
    public final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>public.summary</code>.
     */
    public final Summary SUMMARY = Summary.SUMMARY;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppState.APP_STATE,
            FeedItem.FEED_ITEM,
            SavedItem.SAVED_ITEM,
            Source.SOURCE,
            Summary.SUMMARY,
            User.USER
        );
    }
}
