/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.AppState;
import jooq.tables.FeedItem;
import jooq.tables.SavedItem;
import jooq.tables.Source;
import jooq.tables.Summary;
import jooq.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.app_state</code>.
     */
    public static final AppState APP_STATE = AppState.APP_STATE;

    /**
     * The table <code>public.feed_item</code>.
     */
    public static final FeedItem FEED_ITEM = FeedItem.FEED_ITEM;

    /**
     * The table <code>public.saved_item</code>.
     */
    public static final SavedItem SAVED_ITEM = SavedItem.SAVED_ITEM;

    /**
     * The table <code>public.source</code>.
     */
    public static final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>public.summary</code>.
     */
    public static final Summary SUMMARY = Summary.SUMMARY;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
